---

- hosts: all
  become: yes
  tasks:
  - name: Schedule reboot for second Tuesday of each month at 9 PM
    cron:
      name: "Daily reboot"
      minute: "0"
      hour: "21"
      weekday: "2"
      month: "*"
      day: "8-14"
      job: "/sbin/shutdown -r now"
      user: root
      
  - name: Output confirmation message
    debug:
     msg: "Reboot scheduled for {{ inventory_hostname }} on the second Tuesday of each month at 9 PM"
