---
- hosts: all
  become: true
  tasks:
  - name: Update and upgrade apt packages
    become: yes
    apt:
       update_cache: yes
       upgrade: yes
       cache_valid_time: 86400 #One day
    when: ansible_os_family == "Debian"
       
  - name: Check that the reboot-requied exists      
    stat:        
      path: /var/run/reboot-required      
    register: p    
  - debug:        
      msg: "Reboot required"      
    when: p.stat.exists

  - name: Update yum cache
    ansible.builtin.dnf:
      name: '*'
      state: latest
    when: ansible_os_family == "RedHat"